### ISSUE TITLE
TypesScript definitions

### ISSUE THREAD

**Issue by XaeroDegreaz** [ismamz/react-bootstrap-icons#1]
Thanks for your work on this. Will you also add TS definitions?

**Comment by ismamz** [comment]
Hi! Yes, I'll add it soon!

**Comment by huhusseyn** [comment]
May i help with that? im really new at github.

**Comment by ismamz** [comment]
@XaeroDegreaz @huhusseyn New version released! Let me know if there is anything else to improve.
