### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by theEpsilon** [ismamz/react-bootstrap-icons#10]
Very nice framework! Sadly, we cannot use it in our project as long as no licensing information is provided. If you intended your work to be open source, please consider adding an [open source license](https://opensource.org/licenses).

**Comment by ismamz** [comment]
Hi! I've added it: https://github.com/ismamz/react-bootstrap-icons/blob/master/LICENSE.md
Keep in mind that [Bootstrap Icons are licensed MIT](https://github.com/twbs/icons/blob/main/LICENSE.md) too.
