### ISSUE TITLE
Importing a single Icon is not working with webpack

### ISSUE THREAD

**Issue by SharadKumar** [ismamz/react-bootstrap-icons#12]
Please note the example:
https://codesandbox.io/s/upbeat-beaver-7pfsj?file=/pages/index.js

```jsx
import Link from "next/link";
import { Gear } from "react-bootstrap-icons";

export default function IndexPage() {
  return (
    <div>
      <p>
        Hello World. <Gear />
      </p>

      <Link href="/about">
        <a>About</a>
      </Link>
    </div>
  );
}
```

Then see:
https://7pfsj.sse.codesandbox.io/_next/static/chunks/pages/index.js?ts=1603596442978

ie when I find, I get 4480 = 1120x4 for each icon.

16.4MB resources ie 2.3MB transferred.

![image](https://user-images.githubusercontent.com/5488144/97098286-609ee700-16cf-11eb-80e5-48eb9bc6b227.png)

![image](https://user-images.githubusercontent.com/5488144/97098251-dfdfeb00-16ce-11eb-84d3-f54d13204921.png)

**Comment by ismamz** [comment]
Hi @SharadKumar That only happens in development mode. In production only the icons that are being used will remain
