### ISSUE TITLE
Add support for title prop

### ISSUE THREAD

**Issue by tkrotoff** [ismamz/react-bootstrap-icons#13]
Example:

```JSX
const AlarmFill = forwardRef(({ title, color, size, ...rest }, ref) => {
  return (
    <svg
      ...
    >
      {title ? <title>{title}</title> : null}
      ...
    </svg>
  );
});
```

`<title>` acts kind of like img alt="" and/or div title="".

SVGR (which is pretty popular) proposes this option: https://react-svgr.com/playground/?titleProp=true
btw they have a nice command line tool that you can probably use to generate the JSX.

Thank you for your awesome work!

**Comment by FlorianCassayre** [comment]
I'm also very interested in this feature, for accessibility reasons. Thank you in advance!
