### ISSUE TITLE
Export icon Props from TypeScript definition

### ISSUE THREAD

**Issue by tkrotoff** [ismamz/react-bootstrap-icons#14]
Here: https://github.com/ismamz/react-bootstrap-icons/blob/v1.1.0/src/index.d.ts#L4

This would allow to reuse/extends Props.

`interface Props` => `export interface Props`.

**Comment by ismamz** [comment]
Hi @tkrotoff thanks for the suggestion. I've fixed [here](https://github.com/ismamz/react-bootstrap-icons/commit/c43ec0407ee4f49a0dee038eed0cc13427320d19)!
