### ISSUE TITLE
NPM Install Error: React 16.8.6 vs 17.0.1 Dependency

### ISSUE THREAD

**Issue by saurav2799** [ismamz/react-bootstrap-icons#18]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxxxxx
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from react-bootstrap-icons@1.2.2
npm ERR! node_modules/react-bootstrap-icons
npm ERR!   react-bootstrap-icons@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by chrispinkney** [comment]
Looks like it needs to be updated for react 17.0.1

**Comment by ismamz** [comment]
@saurav2799 @chrispinkney It should be working now. Also, I've update de icons library to the last version (1.2.2). Thanks for reporting!
