### ISSUE TITLE
1.7.x support

### ISSUE THREAD

**Issue by ondrejkolin** [ismamz/react-bootstrap-icons#29]
Hi! 

I know this is really rude to ask for (as anyone can contribute), but are there any plans for 1.7.x release? 

Pull request could be a bit hard for me, but If you point me and mentor me, I could maybe help there as well. 

Very thankful for everything so far :-)

**Comment by lkwr** [comment]
Hey,

I created a pull request for the release 1.7.2. Check it out #30
