### ISSUE TITLE
Missing icon, PeopleCircle

### ISSUE THREAD

**Issue by mssaxian** [ismamz/react-bootstrap-icons#31]
Ok. As I was typing this I think I see what happened. Appears that PeopleCircle was renamed to PersonCircle. This makes sense as the icon presents a singular circular person icon. However, the change broke my build and took me a while to figure out what happened. Is there a way to avoid this frustration in the future if a similar change occurs?

**Comment by ismamz** [comment]
@mssaxian Hi! What was your previous version? Keep in mind that this is a decision from the original library and minor changes can rename icons. We sync this package version number with the original library for consistency.
