### ISSUE TITLE
Need fixes from upstream regarding misaligned icons

### ISSUE THREAD

**Issue by borzaka** [ismamz/react-bootstrap-icons#33]
The icons are misaligned when used in different components. See:
- https://github.com/twbs/icons/issues/82
- https://github.com/twbs/icons/issues/921

`.bi` class is using a style which fixes this issue:
```
.bi {
    display: inline-block;
    vertical-align: -0.125em;
}
```

I would like to see this fix implemented. Thank you.

**Comment by ismamz** [comment]
Hi @borzaka, you can add whatever class you like to Icon components. What fix would you like yo see?

**Comment by borzaka** [comment]
I have used like this:
`<Fan className="bi" />`

But of course I don't have styles for the `bi` class, because I have imported the icon like this:
`import { Fan } from "react-bootstrap-icons";`

And not with font icons:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">`
Which contains the fix.

So maybe I'am left with creating this style somewhere in my project?
```
.bi {
    display: inline-block;
    vertical-align: -0.125em;
}
```

**Comment by carrymisss** [comment]
@borzaka yes, just add your own classes and write your own styles

**Comment by borzaka** [comment]
I see, thank you.
