### ISSUE TITLE
Update to v1.9.0

### ISSUE THREAD

**Issue by nosecreek** [ismamz/react-bootstrap-icons#43]
Would love to see an update to 1.9.0, to add it's new icons

**Comment by ismamz** [comment]
hi @nosecreek i'm working on that

**Comment by nosecreek** [comment]
@ismamz Thanks so much! I had actually just started working on it myself. I made a draft pull request #44 with the work I've done so far. If that's helpful for you let me know, or if you'd rather do it yourself that's fine too. Thanks.
