### ISSUE TITLE
Ability to adjust icon stroke

### ISSUE THREAD

**Issue by syntax-coder** [ismamz/react-bootstrap-icons#5]
Hello 

These icons look great. Is there a way we can control the stroke width of the SVGs to have different variants like light, ultra-light, regular, bold?

**Comment by ismamz** [comment]
Hi @syntax-coder! It's not possible. The [icons are only using `fill`](https://github.com/twbs/icons/issues/220#issuecomment-613253000).

**Comment by inwardmovement** [comment]
Will there be a way some day to customize the stroke width? Maybe with `font-weight` when the icon font is supported?
It would seem like a better way than to provide icons variants (which is what other font libraries do).
