### ISSUE TITLE
Missing Discord Icon

### ISSUE THREAD

**Issue by Quark03** [ismamz/react-bootstrap-icons#51]
The discord icon is missing 🙁
[https://icons.getbootstrap.com/icons/discord/](https://icons.getbootstrap.com/icons/discord/)

I was able to find it in the v1.10.3 sources so I believe it should be available

Thanks!!

**Comment by guoyunhe** [comment]
@Quark03 try this newer package https://github.com/guoyunhe/react-bootstrap-icons-pro

```js
import { BiDiscord } from 'react-bootstrap-icons-pro';
```

**Comment by ismamz** [comment]
It has already been updated to the latest version.

**Comment by infinityredux** [comment]
v1.11.3 is giving errors about the import for the discord icon being missing - it appears the file has been removed?
v1.10.3 does not give these errors.
This is **not** resolved.
