### ISSUE TITLE
Missing Twitter "X" Icon

### ISSUE THREAD

**Issue by eggsforbacon** [ismamz/react-bootstrap-icons#53]
I was wondering when and if a version of this package for bootstrap icons 1.11.1 will be implemented, as right now I'm needing the new X twitter logo as per their new rebranding.

Thanks a lot!

**Comment by guoyunhe** [comment]
@zacwastaken 
I made a new alternative package with up-to-date bootstrap icons https://github.com/guoyunhe/react-bootstrap-icons-pro and it includes what you need:

```js
import { BiTwitterX } from 'react-bootstrap-icons-pro';
```

**Comment by ismamz** [comment]
It has already been updated to the latest version.
