### ISSUE TITLE
Release v1.11.0

### ISSUE THREAD

**Issue by mrdrogdrog** [ismamz/react-bootstrap-icons#54]
Please create a release for bootstrap icons v1.11.0

**Comment by guoyunhe** [comment]
Is this repo still actively maintained?

**Comment by QuocThuanTruong** [comment]
Hey, please create a release for bootstrap icons v1.11.0

**Comment by guoyunhe** [comment]
@mrdrogdrog @QuocThuanTruong I made a new alternative package with up-to-date bootstrap icons https://github.com/guoyunhe/react-bootstrap-icons-pro

**Comment by mrdrogdrog** [comment]
@guoyunhe thank you ❤️
