### ISSUE TITLE
Element Size by Percent

### ISSUE THREAD

**Issue by cerahmed** [ismamz/react-bootstrap-icons#56]
Hi there,

Thanks for the great library.

I'm trying to size my components by percentage of the containing element, so I passed a string `"25%"` to the `size` property without luck. How to properly set the size using strings?

**Comment by ismamz** [comment]
Hi @cerahmed, apologies for the delay. It should work like this:

```html
<div style="width: 300px; height: 300px;">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="50%" height="50%" fill="currentColor">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M9.283 4.002H7.971L6.072 5.385v1.271l1.834-1.318h.065V12h1.312z" />
  </svg>
</div>
```
