### ISSUE TITLE
no Copy icon

### ISSUE THREAD

**Issue by jozhuare99** [ismamz/react-bootstrap-icons#58]
there should be a Copy icon

**Comment by samkanje** [comment]
Was looking for the Copy icon too.

**Comment by jerry-flam** [comment]
I also need this icon. I used the svg directly from here: https://icons.getbootstrap.com/icons/copy/ as a workaround

**Comment by guoyunhe** [comment]
@samkanje @jozhuare99 @jerry-flam I made a new alternative package with up-to-date bootstrap icons https://www.npmjs.com/package/react-bootstrap-icons-pro

**Comment by ismamz** [comment]
The library has been updated. Apologies for the delay and thank you for bringing it to my attention 👍
