### ISSUE TITLE
Add default Bootstrap Icons classes to React components

### ISSUE THREAD

**Issue by borzaka** [ismamz/react-bootstrap-icons#61]
On the official Bootstrap Icons site, if you go to the selected icon's page, you can copy the SVG code, which contains default classes on them:
```html
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-archive-fill" viewBox="0 0 16 16">
  <path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1M.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8z"/>
</svg>
```
https://icons.getbootstrap.com/icons/archive-fill/

It's the same, if you were use the Icon font: `<i class="bi bi-archive-fill"></i> `

I would like to see these classes on the React components as well, because most of the time we need to style these icons, and it would be nice to have that classes on by default. Otherwise I always has to add manually: `<Gear className="bi" />`

**Comment by ismamz** [comment]
Hi @borzaka, the new release includes this feature. Thanks for your feedback!
