### ISSUE TITLE
Importing single icon makes 900K bundle

### ISSUE THREAD

**Issue by stepancheg** [ismamz/react-bootstrap-icons#7]
Repro: https://github.com/stepancheg/react-bootstrap-icons-size-repro

```
$ yarn build-client
...
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  bundle.js (897 KiB)
```

It is a default setup of webpack from webpack website, webpack is invoked with `-p` and I'm out of ideas how to fix the size issue (I'm new to web development).

So it is either issue with this module or with my setup.

If it is `react-bootstrap-icons` then fix it, please?

If it is a problem with my setup, I guess it would be a common mistake, so can you please write some hints on how to use the library properly?

**Comment by ismamz** [comment]
Hi @stepancheg. It is a problem with this module and it is already fixed in the next version. Thank you very much for reporting this very important error and for taking the time to test it.

**Comment by stepancheg** [comment]
Thank you!
